# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [9]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Dell/anaconda3/Library/include
    lib directory: C:/Users/Dell/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    

#### 3. Create a null vector of size 10

In [25]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [39]:
a=np.array([1,2,3,4,5])
print(a.size*a.itemsize,"bytes")

20 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [45]:
np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\dell\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [55]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [57]:
np.arange(10,49)
np.arange(10,49,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### 8.  Reverse a vector (first element becomes last)

In [67]:
arr=np.array([1,2,3,4,5])
print(np.flipud(arr))

[5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [80]:
x=np.random.randint(0,9,(3,3))
print(x)

[[2 2 8]
 [0 6 2]
 [4 7 0]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [86]:
y=np.array([1,2,0,0,4,0])
print(np.nonzero(y))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [98]:
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [109]:
arr=np.random.rand(3,3,3)
print(arr)

[[[0.4338333  0.68312898 0.96621283]
  [0.70448131 0.91399424 0.10755844]
  [0.87717214 0.64392741 0.34672848]]

 [[0.81623464 0.78651802 0.16862476]
  [0.02817098 0.25754101 0.01716937]
  [0.71349579 0.88966473 0.05822014]]

 [[0.2458354  0.31676114 0.95584765]
  [0.48947849 0.65832328 0.364179  ]
  [0.74712191 0.5447696  0.22774711]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [121]:
arr=np.random.random((10,10))
print(np.min(arr))
print(np.max(arr))

0.004166057146956503
0.9890700912075594


#### 14. Create a random vector of size 30 and find the mean value

In [131]:
arr=np.random.random(30)
print(np.mean(arr))

0.5276158755057143


#### 15. Create a 2d array with 1 on the border and 0 inside

In [141]:
arr=np.ones((3,3))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [160]:
arr1=np.ones((3,3))
np.pad(arr1,pad_width = 1, mode = 'constant',constant_values = 0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [166]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [180]:
arr=np.diag([1,2,3,4],-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [188]:
arr1 = np.zeros((8,8),dtype=int)
arr1[1::2,::2] = 1
arr1[::2,1::2] = 1
print(arr1)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [190]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)