In [1]:
import numpy as np

In [3]:
arr = np.array([[ 1, 2, 3],
                [ 4, 5, 6]])
print("Array is of type: ", type(arr))
print("No. of dimensions: ", arr.ndim)
print("Shape of array: ", arr.shape)
print("Size of array: ", arr.size)
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int32


In [5]:
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print("Array created using passed list:\n", a)
b = np.array((1 , 3, 2))
print("\nArray created using passed tuple:\n", b)
c = np.zeros((3, 4))
print("\nAn array initialized with all zeros:\n", c)
d = np.full((3, 3), 6, dtype = 'complex')
print("\nAn array initialized with all 6s. Array type is complex:\n", d)

Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]

Array created using passed tuple:
 [1 3 2]

An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An array initialized with all 6s. Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [7]:
e = np.random.random((2,2))
print("\nA random array:\n", e)
f = np.arange(0, 30, 5)
print("\nA sequential array with steps of 5:\n", f)
g = np.linspace(0, 5, 10)
print("\nA sequential array with 10 values between 0 and 5:\n", g)
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
newarr = arr.reshape(2, 2, 3)
print("\nOriginal array:\n", arr)
print("Reshaped array:\n", newarr)
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()
print("\nOriginal array:\n", arr)
print("Fattened array:\n", flarr)


A random array:
 [[0.81413745 0.55489365]
 [0.43699142 0.83276527]]

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

A sequential array with 10 values between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]

Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


In [9]:
arr1 = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
temp = arr1[:2, ::2]
print("Array with first 2 rows and alternate columns(0 and 2):\n", temp)
temp = arr1[[0, 1, 2, 3], [3, 2, 1, 0]]
print("\nElements at indices (0, 3), (1, 2), (2, 1), (3, 0):\n", temp)
cond = arr1 > 0    
temp = arr1[cond]
print("\nElements greater than 0:\n", temp)

Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1), (3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [11]:
a1 = np.array([1, 2, 5, 3])
print("Adding 1 to every element:", a1+1)
print("Subtracting 3 from each element:", a1-3)
print("Multiplying each element by 10:", a1*10)
print("Squaring each element:", a1**2)
a1 *= 2
print("Doubled each element of original array:", a1)
a1 = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print("\nOriginal array:\n", a1)
print("Transpose of array:\n", a1.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [13]:
arr2 = np.array([[1, 5, 6], 
                [4, 7, 2], 
                [3, 1, 9]])
print("Largest element is:", arr2.max())
print("Row-wise maximum elements:", arr2.max(axis = 1))
print("Column-wise minimum elements:", arr2.min(axis = 0))
print("Sum of all array elements:", arr2.sum())
print("Cumulative sum along each row:\n", arr2.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [15]:
a2 = np.array([[1, 2], 
              [3, 4]])
b2 = np.array([[4, 3], 
              [2, 1]])
print("Array sum:\n", a2 + b2)
print("Array multiplication:\n", a2*b2)
print("Matrix multiplication:\n", a2.dot(b2))

Array sum:
 [[5 5]
 [5 5]]
Array multiplication:
 [[4 6]
 [6 4]]
Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [17]:
a3 = np.array([0, np.pi/2, np.pi])
print("Sine values of array elements:", np.sin(a3))
a3 = np.array([0, 1, 2, 3])
print("Exponent of array elements:", np.exp(a3))
print("Square root of array elements:", np.sqrt(a3))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [19]:
a4 = np.array([[1, 4, 2],
              [3, 4,6],
              [0, -1, 5]])
print("Array elements in sorted order:\n", np.sort(a4, axis = None))
print("Row-wise sorted array:\n", np.sort(a4, axis = 1))
print("Column wise sort by applying merge-sort:\n", np.sort(a4, axis = 0, kind = 'mergesort'))
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
arr4 = np.array(values, dtype = dtypes)
print("\nArray sorted by names:\n", np.sort(arr4, order = 'name'))
print("Array sorted by grauation year and then cgpa:\n", np.sort(arr4, order = ['grad_year', 'cgpa']))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
Column wise sort by applying merge-sort:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by grauation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


In [21]:
a5 = np.array([[1, 2],
              [3, 4]])

b5 = np.array([[5, 6],
              [7, 8]])
print("Vertical stacking:\n", np.vstack((a5, b5)))
print("\nHorizontal stacking:\n", np.hstack((a5, b5)))
c2 = [5, 6]
print("\nColumn stacking:\n", np.column_stack((a5, c2)))
print("\nConcatenating to 2nd axis:\n", np.concatenate((a5, b5), 1))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]

Column stacking:
 [[1 2 5]
 [3 4 6]]

Concatenating to 2nd axis:
 [[1 2 5 6]
 [3 4 7 8]]


In [23]:
a6 = np.array([[1, 3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10, 12]])
print("Splitting along horizontal axis into 2 parts:\n", np.hsplit(a6, 2))
print("\nSplitting along vertical axis into 2 parts:\n", np.vsplit(a6, 2))

Splitting along horizontal axis into 2 parts:
 [array([[1, 3, 5],
       [2, 4, 6]]), array([[ 7,  9, 11],
       [ 8, 10, 12]])]

Splitting along vertical axis into 2 parts:
 [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [25]:
a7 = np.array([[1,2,3,4],[7,6,2,0]])
print(a7)
print(np.min(a7))
print(np.min(a7,axis=0))
print(np.min(a7,axis=1))

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [29]:
i = np.array([1,2,3,4,5])
m = sum(i)/5
print(m)
print(np.mean(i))
print(np.mean(a7,axis=0))
print(np.mean(a7,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [31]:
j = np.array([1,5,4,2,0])
print(np.median(j))
print(np.mean(j))
w = np.array([1,1,1,1,1])
print(np.average(j,weights=w))
u = np.mean(j)
myStd = np.sqrt(np.mean(abs(j-u)**2))
print(myStd)
dev= np.std(j)
print(dev)
print(myStd**2)
print(np.var(j))

2.0
2.4
2.4
1.854723699099141
1.854723699099141
3.440000000000001
3.4400000000000004


In [33]:
k = np.arange(10) + 5
print(k)
np.random.seed(1)
np.random.shuffle(k)
print(k)
k = np.random.randn(2,3)
print(k)
k = np.random.randint(5,10,3)
print(k)
element = np.random.choice([1,4,3,2,11,27])
print(element)

[ 5  6  7  8  9 10 11 12 13 14]
[ 7 14 11  9  5  8  6 12 13 10]
[[ 1.5827523  -1.04514683  0.25759352]
 [-1.9593946  -1.50780766 -0.31529207]]
[7 9 6]
4
